POST http://localhost:3005/api/deliverynote/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODIyNDQ2NzRjOTU5NGZkOGFhZjAyZTkiLCJpYXQiOjE3NDc2NzE1MDEsImV4cCI6MTc0NzY3ODcwMX0.0nP3kmlhEMI1adJe1GFkyRM9zzJ_P4vtfGN97nNUGhk
Content-Type: application/json

{
    "project_name": "project_1A",
    "number": "03",
    "people": [{
        "name": "Juan Piedra",
        "rol": "transportista",
        "hours": "8" 
    }],
    "materials": [{
        "name": "Placas Aluminio",
        "units": "20"
    }]
}

###
GET http://localhost:3005/api/deliverynote/6827603cf389fe9d3fc9a0d9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODIyNDQ2NzRjOTU5NGZkOGFhZjAyZTkiLCJpYXQiOjE3NDc1ODAyOTIsImV4cCI6MTc0NzU4NzQ5Mn0.7HXMNP6ZNxoAFtgGDvAQum3Y4aos902O8wlhJ34ZtUE

###
GET http://localhost:3005/api/deliverynote/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODIyNDQ2NzRjOTU5NGZkOGFhZjAyZTkiLCJpYXQiOjE3NDc2NzE1MDEsImV4cCI6MTc0NzY3ODcwMX0.0nP3kmlhEMI1adJe1GFkyRM9zzJ_P4vtfGN97nNUGhk

###
GET http://localhost:3005/api/deliverynote/pdf/682a083461e457673676b4b5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODIyNDQ2NzRjOTU5NGZkOGFhZjAyZTkiLCJpYXQiOjE3NDc1ODAyOTIsImV4cCI6MTc0NzU4NzQ5Mn0.7HXMNP6ZNxoAFtgGDvAQum3Y4aos902O8wlhJ34ZtUE

###
PATCH http://localhost:3005/api/deliverynote/sign/6827603cf389fe9d3fc9a0d9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODIyNDQ2NzRjOTU5NGZkOGFhZjAyZTkiLCJpYXQiOjE3NDc1ODAyOTIsImV4cCI6MTc0NzU4NzQ5Mn0.7HXMNP6ZNxoAFtgGDvAQum3Y4aos902O8wlhJ34ZtUE
Content-Type: application/json

{
    "signature": "abcdefghij"
}

###
DELETE http://localhost:3005/api/deliverynote/delete/682b657fa6a9c5fc9cf49389
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODIyNDQ2NzRjOTU5NGZkOGFhZjAyZTkiLCJpYXQiOjE3NDc2NzE1MDEsImV4cCI6MTc0NzY3ODcwMX0.0nP3kmlhEMI1adJe1GFkyRM9zzJ_P4vtfGN97nNUGhk
