 
###
POST http://localhost:3005/api/users/register
Content-Type: application/json

{
    "name": "Jaime",
    "email": "carpr@gmail.com",
    "password": "jaime123"
}

###
PUT http://localhost:3005/api/users/validation
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2VhODEwNzM1ZGU4MTA0M2MwMGY1OTEiLCJpYXQiOjE3NDM0MjE3MDMsImV4cCI6MTc0MzQyODkwM30.ANSzGfN8KXD4zAcA1zCOaa3-_qJt33_7dMqr52R-C8I
Content-Type: application/json

{
    "email": "carpr@gmail.com",
    "password": "jaime123",
    "code": 605327
}

###
POST http://localhost:3005/api/users/login
Content-Type: application/json

{
    "email": "edpr@gmail.com",
    "password": "jaime123"
}

###
PATCH http://localhost:3005/api/storage/logo
Content-Type: multipart/form-data; boundary=boundary123

--boundary123
Content-Disposition: form-data; name="image"; filename="LegoLogo.jpg"
Content-Type: image/jpeg

< ./LegoLogo.jpg
--boundary123--

###
GET http://localhost:3005/api/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2VhODg5YmNlMWNmY2M2NzgwMjAwYTciLCJpYXQiOjE3NDM0MjM2NDMsImV4cCI6MTc0MzQzMDg0M30.53ZT7bcyccBxCzQ1NsP8gjvLGT4ICOtoDypMiEYp3Ig

###
DELETE http://localhost:3005/api/users/hardDelete
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2VhODEwNzM1ZGU4MTA0M2MwMGY1OTEiLCJpYXQiOjE3NDM0MjE3MDMsImV4cCI6MTc0MzQyODkwM30.ANSzGfN8KXD4zAcA1zCOaa3-_qJt33_7dMqr52R-C8I

###
PATCH http://localhost:3005/api/users/softDelete
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2VhODg5YmNlMWNmY2M2NzgwMjAwYTciLCJpYXQiOjE3NDM0MjM2NDMsImV4cCI6MTc0MzQzMDg0M30.53ZT7bcyccBxCzQ1NsP8gjvLGT4ICOtoDypMiEYp3Ig