###
POST http://localhost:3005/api/users/register
Content-Type: application/json

{
    "name": "user_1",
    "email": "user_1@gmail.com",
    "password": "user1234",
    "autonomous": true
}

###
PUT http://localhost:3005/api/users/validation
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODIyNDQ2NzRjOTU5NGZkOGFhZjAyZTkiLCJpYXQiOjE3NDc2NzE1MDEsImV4cCI6MTc0NzY3ODcwMX0.0nP3kmlhEMI1adJe1GFkyRM9zzJ_P4vtfGN97nNUGhk
Content-Type: application/json

{
    "email": "user_A@gmail.com",
    "password": "user1234",
    "code": 649149
}

###
POST http://localhost:3005/api/users/login
Content-Type: application/json

{
    "email": "user_A@gmail.com",
    "password": "user1234"
}

###
PATCH http://localhost:3005/api/users/update
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODIyNDA0OGY5N2UzOTkxNDI1ZTlhYWIiLCJpYXQiOjE3NDcwNzUyNDAsImV4cCI6MTc0NzA4MjQ0MH0.gZvtBijajxGIN_8kQa0XqMFf48l24RtlQVCbMMcLWO0
Content-Type: application/json

{
    "name": "user_1A",
    "lastName": "resu",
    "nif": "111111111",
    "address": "Paper Street, 0"
}

###
PATCH http://localhost:3005/api/company/onBoarding
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODFiNzIzZjA4YThiNTM0ZWZjZGZiZjkiLCJpYXQiOjE3NDY2MjkxODMsImV4cCI6MTc0NjYzNjM4M30.VIYrdA_dBUjwaHUT29uaatcPwsfVua8D_DFBefeK2mA
Content-Type: application/json

{
    "name": "company_1",
    "cif": "999999999"
}

###
PATCH http://localhost:3005/api/storage/logo
Content-Type: multipart/form-data; boundary=boundary123

--boundary123
Content-Disposition: form-data; name="image"; filename="LegoLogo.jpg"
Content-Type: image/jpeg

< ./LegoLogo.jpg
--boundary123--

###
GET http://localhost:3005/api/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2VhOGQwODA1OGRkYTE2OThlYWRhNjAiLCJpYXQiOjE3NDM0MjQ3NzYsImV4cCI6MTc0MzQzMTk3Nn0.oIJWqPIYg91cSdqTK91Xy6Jsmtw22w-S36q9MvT0YqI

###
DELETE http://localhost:3005/api/users/delete?soft=false
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODIyNDQ3MjRjOTU5NGZkOGFhZjAyZWIiLCJpYXQiOjE3NDcwNzYyMTAsImV4cCI6MTc0NzA4MzQxMH0.8A1-02f9U6kjif3rKubyHLDC-955Fkszfog8SuozmZY